import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        stitch: {
          surface: "#fdf4f8",
          "surface-bright": "#fdf4f8",
          "on-surface": "#1c191c",
          "on-background": "#1c191c",
          background: "#fdf4f8",
          "surface-variant": "#e6dde2",
          "on-surface-variant": "#543a4f",
          tertiary: "#6b3f5a",
          secondary: "#9c2d6a",
          primary: "#8e1f5c",
          "on-primary": "#ffffff",
          "primary-container": "#b8436a",
          "on-primary-container": "#fff8fb",
          "primary-fixed": "#ffd6ec",
          "primary-fixed-dim": "#ffb3d5",
          "on-primary-fixed": "#380020",
          "surface-container": "#f1e8ed",
          "surface-container-low": "#f8eef4",
          "surface-container-high": "#ebe2e7",
          "surface-container-highest": "#e6dde2",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed": "#ffd6e8",
          "on-secondary": "#ffffff",
          "on-secondary-container": "#7a1048",
          "tertiary-container": "#8b5d7a",
          "tertiary-fixed": "#ffdcea",
          "on-secondary-fixed": "#3d001e",
          "on-secondary-fixed-variant": "#7e1a4d",
          "on-tertiary-fixed": "#2a0a1f",
          "on-tertiary-fixed-variant": "#593244",
          "on-primary-fixed-variant": "#7a1248",
          "secondary-container": "#f598c4",
          "outline-variant": "#dbb5ce",
          outline: "#886378",
          "inverse-surface": "#312d30",
          "inverse-on-surface": "#f4ebf0",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          bg: "#F8EEF3",
          "bg-secondary": "#FDF5F9",
          primary: "#B83C7A",
          "primary-dark": "#8E1F5C",
          text: "#5A3650",
          heading: "#2A2027",
          border: "#E8D8E2",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        display: ["var(--font-noto-serif)", "Georgia", "serif"],
        headline: ["var(--font-noto-serif)", "Georgia", "serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      boxShadow: {
        soft: "0 4px 24px -4px rgba(42, 32, 39, 0.08), 0 8px 32px -8px rgba(184, 60, 122, 0.12)",
        card: "0 2px 12px rgba(42, 32, 39, 0.06)",
        editorial: "0 8px 24px rgba(142, 31, 92, 0.08)",
        "nav-up": "0 -8px 24px rgba(142, 31, 92, 0.08)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
