import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Rate-card brand palette: deep wine maroon + warm gold-tan + cream.
        // Overriding Tailwind's built-in rose/pink scales recolors every
        // literal rose-*/pink-* utility class already used across the app
        // without touching each component file.
        rose: {
          50: "#FBF6F3",
          100: "#F5E9E2",
          200: "#E9D3C6",
          300: "#D8B7A2",
          400: "#BE927A",
          500: "#98685A",
          600: "#74473E",
          700: "#5A322E",
          800: "#4A2A28",
          900: "#412327",
          950: "#2A1517",
        },
        pink: {
          50: "#FBF6F3",
          100: "#F5E9E2",
          200: "#E9D3C6",
          300: "#D8B7A2",
          400: "#BE927A",
          500: "#98685A",
          600: "#74473E",
          700: "#5A322E",
          800: "#4A2A28",
          900: "#412327",
          950: "#2A1517",
        },
        stitch: {
          surface: "#FDF8F3",
          "surface-bright": "#FDF8F3",
          "on-surface": "#2A1517",
          "on-background": "#2A1517",
          background: "#FDF8F3",
          "surface-variant": "#EFE0D3",
          "on-surface-variant": "#6E473E",
          tertiary: "#93594F",
          secondary: "#8A6355",
          primary: "#412327",
          "on-primary": "#FDF8F3",
          "primary-container": "#6E3A38",
          "on-primary-container": "#FDF8F3",
          "primary-fixed": "#E9D3C6",
          "primary-fixed-dim": "#D8B7A2",
          "on-primary-fixed": "#412327",
          "surface-container": "#F5EAE0",
          "surface-container-low": "#FAF3EC",
          "surface-container-high": "#EFE2D5",
          "surface-container-highest": "#E9D9CB",
          "surface-container-lowest": "#FFFFFF",
          "secondary-fixed": "#F0E4D5",
          "on-secondary": "#FDF8F3",
          "on-secondary-container": "#412327",
          "tertiary-container": "#B8917D",
          "tertiary-fixed": "#F0DED0",
          "on-secondary-fixed": "#2A1517",
          "on-secondary-fixed-variant": "#5A322E",
          "on-tertiary-fixed": "#2A1517",
          "on-tertiary-fixed-variant": "#55322A",
          "on-primary-fixed-variant": "#5A322E",
          "secondary-container": "#D8B7A2",
          "outline-variant": "#E3D0BE",
          outline: "#93685A",
          "inverse-surface": "#2A1517",
          "inverse-on-surface": "#F5EAE0",
          gold: "#C6AB97",
          "gold-bright": "#FDB254",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          bg: "#FBF3EC",
          "bg-secondary": "#FDF8F3",
          primary: "#5A322E",
          "primary-dark": "#2A1517",
          text: "#4A332E",
          heading: "#2A1517",
          border: "#E9D9CB",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        display: ["var(--font-noto-serif)", "Georgia", "serif"],
        headline: ["var(--font-noto-serif)", "Georgia", "serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      boxShadow: {
        soft: "0 4px 24px -4px rgba(42, 21, 23, 0.08), 0 8px 32px -8px rgba(65, 35, 39, 0.12)",
        card: "0 2px 12px rgba(42, 21, 23, 0.06)",
        editorial: "0 8px 24px rgba(65, 35, 39, 0.08)",
        "nav-up": "0 -8px 24px rgba(65, 35, 39, 0.08)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
